import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ReactQueryProvider } from './provider'

export const metadata: Metadata = {
  title: "Wall Street AI Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReactQueryProvider>
      <SessionProvider>
        <body>{children}</body>
      </SessionProvider>
      </ReactQueryProvider>
    </html>
  );
}
